### ISSUE TITLE
Error - npm run setup : bower uikit#^3.0.0 ENORESTARGET No tag found that was able to satisfy ^3.0.0

### ISSUE THREAD

**Issue by BobbyBabes** [uikit/uikit-site#31]
`npm run setup` returns error `bower uikit#^3.0.0        ENORESTARGET No tag found that was able to satisfy ^3.0.0`

What's up?
(I'm installing this on a virgin Linux installation.)
```
[BobbyBabes@LadyLuck scripts]# cd ~/dev/web/docs/uikit3/yootheme/uikit-docs
[BobbyBabes@LadyLuck uikit-docs]# npm run setup

> @ setup /home/BobbyBabes/dev/web/docs/uikit3/yootheme/uikit-docs
> npm install && bower update && npm run compile

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN vue-loader@10.3.0 requires a peer of css-loader@* but none was installed.
npm WARN uikit-docs No repository field.
npm WARN uikit-docs No license field.
bower uikit#^3.0.0          not-cached https://github.com/uikit/uikit.git#^3.0.0
bower uikit#^3.0.0             resolve https://github.com/uikit/uikit.git#^3.0.0
bower highlightjs#^9.4.0        cached https://github.com/components/highlightjs.git#9.9.0
bower highlightjs#^9.4.0      validate 9.9.0 against https://github.com/components/highlightjs.git#^9.4.0
bower uikit#^3.0.0        ENORESTARGET No tag found that was able to satisfy ^3.0.0

Additional error details:
Available versions in https://github.com/uikit/uikit.git: 3.0.0-beta.9, 3.0.0-beta.8, 3.0.0-beta.7, 3.0.0-beta.6, 3.0.0-beta.5, 3.0.0-beta.4, 3.0.0-beta.3, 3.0.0-beta.2, 3.0.0-beta.1, 2.27.2, 2.27.2, 2.27.1, 2.27.1, 2.27.0, 2.27.0, 2.26.4, 2.26.4, 2.26.3, 2.26.3, 2.26.2, 2.26.2, 2.26.1, 2.26.1, 2.26.0, 2.26.0, 2.25.0, 2.25.0, 2.24.3, 2.24.3, 2.24.2, 2.24.2, 2.24.1, 2.24.1, 2.24.0, 2.24.0, 2.23.0, 2.23.0, 2.22.0, 2.22.0, 2.21.0, 2.21.0, 2.20.3, 2.20.3, 2.20.2, 2.20.2, 2.20.1, 2.20.1, 2.20.0, 2.20.0, 2.19.0, 2.19.0, 2.18.0, 2.18.0, 2.17.0, 2.17.0, 2.16.2, 2.16.2, 2.16.1, 2.16.1, 2.16.0, 2.16.0, 2.15.0, 2.15.0, 2.14.0, 2.14.0, 2.13.1, 2.13.1, 2.13.0, 2.13.0, 2.12.0, 2.12.0, 2.11.1, 2.11.1, 2.11.0, 2.11.0, 2.10.0, 2.9.0, 2.8.0, 2.7.1, 2.7.0, 2.6.0, 2.5.0, 2.4.0, 2.3.1, 2.3.0, 2.2.0, 2.1.0, 2.0.0, 1.2.1, 1.2.0, 1.1.0, 1.0.2, 1.0.1, 1.0.0

npm ERR! Linux 4.9.7-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/sbin/npm" "run" "setup"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ setup: `npm install && bower update && npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ setup script 'npm install && bower update && npm run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && bower update && npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/BobbyBabes/dev/web/docs/uikit3/yootheme/uikit-docs/npm-debug.log
[BobbyBabes@LadyLuck uikit-docs]# 
```

UPDATE:
And, as per the message above, the contents of `/home/BobbyBabes/dev/web/docs/uikit3/yootheme/uikit-docs/npm-debug.log` :
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/sbin/npm', 'run', 'setup' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle @~presetup: @
6 silly lifecycle @~presetup: no script for presetup, continuing
7 info lifecycle @~setup: @
8 verbose lifecycle @~setup: unsafe-perm in lifecycle true
9 verbose lifecycle @~setup: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/BobbyBabes/dev/web/docs/uikit3/yootheme/uikit-docs/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
10 verbose lifecycle @~setup: CWD: /home/BobbyBabes/dev/web/docs/uikit3/yootheme/uikit-docs
11 silly lifecycle @~setup: Args: [ '-c', 'npm install && bower update && npm run compile' ]
12 silly lifecycle @~setup: Returned: code: 1  signal: null
13 info lifecycle @~setup: Failed to exec setup script
14 verbose stack Error: @ setup: `npm install && bower update && npm run compile`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /home/BobbyBabes/dev/web/docs/uikit3/yootheme/uikit-docs
17 error Linux 4.9.7-1-ARCH
18 error argv "/usr/bin/node" "/usr/sbin/npm" "run" "setup"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error @ setup: `npm install && bower update && npm run compile`
22 error Exit status 1
23 error Failed at the @ setup script 'npm install && bower update && npm run compile'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm install && bower update && npm run compile
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by BobbyBabes** [comment]
Instead of just closing this issue. And in case anyone else runs into this issue. I had found a workaround.
The error occurs during the `bower install` command (in `package.json`).
`bower cache clean; bower install` produced the exact same error.
Then I changed the line `    "uikit": "^3.0.0",` in file `bower.json` with `    "uikit": "^3.0.0-beta.9,"`.
And ran `npm run setup` which completed successfully.
Had to repeat this for all newer versions of UIkit.
