### ISSUE TITLE
Cannot run the site: ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by hopeseekr** [uikit/uikit-site#408]
ReferenceError: Request is not defined
    at getRequest (file:///code/contribs/uikit-site/node_modules/.pnpm/@sveltejs+kit@2.5.3_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.1.6/node_modules/@sveltejs/kit/src/exports/node/index.js:107:2)
    at file:///code/contribs/uikit-site/node_modules/.pnpm/@sveltejs+kit@2.5.3_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.1.6/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27

**Comment by hopeseekr** [comment]
I found the problem. This project requires nodejs 18 but just doesn't specify it anywhere.
